### ISSUE TITLE
Check mode is useless

### ISSUE THREAD

**Issue by tomislacker** [mrlesmithjr/ansible-firewalld#1]
- Code errors when in check mode
- No proper comparison of changes _(probably reasonable, assuming that we don't have failures where we need to comment out your module entirely)_

**Comment by mrlesmithjr** [comment]
Sounds like these issues are related to the `firewalld` module itself?

**Comment by tomislacker** [comment]
@mrlesmithjr I've tried out this role with your recent changes and I believe this issue can be closed, if you disagree, feel free to re-open. Thanks for the support sir!
